//! gmarshal_internal matching `gio/gmarshal-internal.c`.
//!
//! Internal signal marshallers for GIO. These are generated by glib-genmarshal
//! and used by GObject signal infrastructure to dispatch closures with
//! specific type signatures.
//!
//! In this no_std port, we model the marshaller functions as type-safe
//! Rust closures. Each marshaller corresponds to a specific signal signature
//! pattern (e.g., BOOLEAN__OBJECT, VOID__STRING_BOXED).
//!
//! Fully `no_std` compatible using `alloc`.

use crate::gvalue::GValue;
use crate::prelude::*;

/// Signal marshaller trait.
///
/// Each marshaller implementation takes an array of parameter GValues
/// and returns an optional return GValue.
pub trait Marshaller: Send + Sync {
    /// Marshals the signal call.
    ///
    /// `params` contains the instance as the first element, followed by
    /// signal parameters. The return value is stored in `return_value`.
    fn marshal(&self, params: &[GValue]) -> Option<GValue>;
}

/// BOOLEAN:OBJECT marshaller.
///
/// Calls a callback with (instance, object) and returns a boolean.
pub struct BooleanObject<M>
where
    M: Fn(&GValue, &GValue) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanObject<M>
where
    M: Fn(&GValue, &GValue) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanObject<M>
where
    M: Fn(&GValue, &GValue) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 2 {
            return None;
        }
        let result = (self.callback)(&params[0], &params[1]);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// BOOLEAN:VOID marshaller.
///
/// Calls a callback with (instance) and returns a boolean.
pub struct BooleanVoid<M>
where
    M: Fn(&GValue) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanVoid<M>
where
    M: Fn(&GValue) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanVoid<M>
where
    M: Fn(&GValue) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.is_empty() {
            return None;
        }
        let result = (self.callback)(&params[0]);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// BOOLEAN:STRING marshaller.
pub struct BooleanString<M>
where
    M: Fn(&GValue, &str) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanString<M>
where
    M: Fn(&GValue, &str) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanString<M>
where
    M: Fn(&GValue, &str) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 2 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        let result = (self.callback)(&params[0], &s);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// BOOLEAN:UINT marshaller.
pub struct BooleanUint<M>
where
    M: Fn(&GValue, u32) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanUint<M>
where
    M: Fn(&GValue, u32) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanUint<M>
where
    M: Fn(&GValue, u32) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 2 {
            return None;
        }
        let result = (self.callback)(&params[0], params[1].get_uint());
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// VOID:VOID marshaller.
pub struct VoidVoid<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidVoid<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidVoid<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.is_empty() {
            return None;
        }
        (self.callback)(&params[0]);
        None
    }
}

/// VOID:OBJECT_OBJECT marshaller.
pub struct VoidObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        (self.callback)(&params[0], &params[1], &params[2]);
        None
    }
}

/// VOID:STRING_BOXED marshaller.
pub struct VoidStringBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 2 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s);
        None
    }
}

/// VOID:STRING_VARIANT marshaller.
pub struct VoidStringVariant<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringVariant<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringVariant<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 2 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s);
        None
    }
}

/// VOID:UINT_UINT_UINT marshaller.
pub struct VoidUintUintUint<M>
where
    M: Fn(&GValue, u32, u32, u32) + Send + Sync,
{
    callback: M,
}

impl<M> VoidUintUintUint<M>
where
    M: Fn(&GValue, u32, u32, u32) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidUintUintUint<M>
where
    M: Fn(&GValue, u32, u32, u32) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 4 {
            return None;
        }
        (self.callback)(
            &params[0],
            params[1].get_uint(),
            params[2].get_uint(),
            params[3].get_uint(),
        );
        None
    }
}

/// VOID:INT_INT_INT marshaller.
pub struct VoidIntIntInt<M>
where
    M: Fn(&GValue, i32, i32, i32) + Send + Sync,
{
    callback: M,
}

impl<M> VoidIntIntInt<M>
where
    M: Fn(&GValue, i32, i32, i32) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidIntIntInt<M>
where
    M: Fn(&GValue, i32, i32, i32) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 4 {
            return None;
        }
        (self.callback)(
            &params[0],
            params[1].get_int(),
            params[2].get_int(),
            params[3].get_int(),
        );
        None
    }
}

/// INT:OBJECT marshaller.
pub struct IntObject<M>
where
    M: Fn(&GValue, &GValue) -> i32 + Send + Sync,
{
    callback: M,
}

impl<M> IntObject<M>
where
    M: Fn(&GValue, &GValue) -> i32 + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for IntObject<M>
where
    M: Fn(&GValue, &GValue) -> i32 + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 2 {
            return None;
        }
        let result = (self.callback)(&params[0], &params[1]);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_INT);
        v.set_int(result);
        Some(v)
    }
}

/// VOID:STRING_STRING_STRING_FLAGS marshaller.
pub struct VoidStringStringStringFlags<M>
where
    M: Fn(&GValue, &str, &str, &str, u32) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringStringStringFlags<M>
where
    M: Fn(&GValue, &str, &str, &str, u32) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringStringStringFlags<M>
where
    M: Fn(&GValue, &str, &str, &str, u32) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 5 {
            return None;
        }
        let s1 = params[1].get_string().unwrap_or("").to_string();
        let s2 = params[2].get_string().unwrap_or("").to_string();
        let s3 = params[3].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s1, &s2, &s3, params[4].get_uint());
        None
    }
}

/// VOID:STRING_BOOLEAN marshaller.
pub struct VoidStringBoolean<M>
where
    M: Fn(&GValue, &str, bool) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringBoolean<M>
where
    M: Fn(&GValue, &str, bool) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringBoolean<M>
where
    M: Fn(&GValue, &str, bool) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s, params[2].get_boolean());
        None
    }
}

/// VOID:STRING_INT64_INT64 marshaller.
pub struct VoidStringInt64Int64<M>
where
    M: Fn(&GValue, &str, i64, i64) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringInt64Int64<M>
where
    M: Fn(&GValue, &str, i64, i64) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringInt64Int64<M>
where
    M: Fn(&GValue, &str, i64, i64) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 4 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s, params[2].get_int64(), params[3].get_int64());
        None
    }
}

/// VOID:POINTER_INT_STRING marshaller.
pub struct VoidPointerIntString<M>
where
    M: Fn(&GValue, i32, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidPointerIntString<M>
where
    M: Fn(&GValue, i32, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidPointerIntString<M>
where
    M: Fn(&GValue, i32, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 4 {
            return None;
        }
        let s = params[3].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], params[2].get_int(), &s);
        None
    }
}

/// VOID:VARIANT_BOXED marshaller.
pub struct VoidVariantBoxed<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidVariantBoxed<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidVariantBoxed<M>
where
    M: Fn(&GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.is_empty() {
            return None;
        }
        (self.callback)(&params[0]);
        None
    }
}

/// VOID:OBJECT_VARIANT marshaller.
pub struct VoidObjectVariant<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidObjectVariant<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidObjectVariant<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        (self.callback)(&params[0], &params[2]);
        None
    }
}

/// VOID:OBJECT_OBJECT_STRING_STRING_VARIANT marshaller.
pub struct VoidObjectObjectStringStringVariant<M>
where
    M: Fn(&GValue, &GValue, &str, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidObjectObjectStringStringVariant<M>
where
    M: Fn(&GValue, &GValue, &str, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidObjectObjectStringStringVariant<M>
where
    M: Fn(&GValue, &GValue, &str, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 5 {
            return None;
        }
        let s1 = params[2].get_string().unwrap_or("").to_string();
        let s2 = params[3].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &params[1], &s1, &s2);
        None
    }
}

/// VOID:OBJECT_OBJECT_VARIANT_BOXED marshaller.
pub struct VoidObjectObjectVariantBoxed<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidObjectObjectVariantBoxed<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidObjectObjectVariantBoxed<M>
where
    M: Fn(&GValue, &GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 5 {
            return None;
        }
        (self.callback)(&params[0], &params[1]);
        None
    }
}

/// VOID:OBJECT_OBJECT_ENUM marshaller.
pub struct VoidObjectObjectEnum<M>
where
    M: Fn(&GValue, &GValue, i32) + Send + Sync,
{
    callback: M,
}

impl<M> VoidObjectObjectEnum<M>
where
    M: Fn(&GValue, &GValue, i32) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidObjectObjectEnum<M>
where
    M: Fn(&GValue, &GValue, i32) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 4 {
            return None;
        }
        (self.callback)(&params[0], &params[1], params[3].get_int());
        None
    }
}

/// VOID:ENUM_OBJECT marshaller.
pub struct VoidEnumObject<M>
where
    M: Fn(&GValue, i32, &GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidEnumObject<M>
where
    M: Fn(&GValue, i32, &GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidEnumObject<M>
where
    M: Fn(&GValue, i32, &GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        (self.callback)(&params[0], params[1].get_int(), &params[2]);
        None
    }
}

/// VOID:ENUM_OBJECT_OBJECT marshaller.
pub struct VoidEnumObjectObject<M>
where
    M: Fn(&GValue, i32, &GValue, &GValue) + Send + Sync,
{
    callback: M,
}

impl<M> VoidEnumObjectObject<M>
where
    M: Fn(&GValue, i32, &GValue, &GValue) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidEnumObjectObject<M>
where
    M: Fn(&GValue, i32, &GValue, &GValue) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 4 {
            return None;
        }
        (self.callback)(&params[0], params[1].get_int(), &params[2], &params[3]);
        None
    }
}

/// VOID:BOOLEAN_BOXED marshaller.
pub struct VoidBooleanBoxed<M>
where
    M: Fn(&GValue, bool) + Send + Sync,
{
    callback: M,
}

impl<M> VoidBooleanBoxed<M>
where
    M: Fn(&GValue, bool) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidBooleanBoxed<M>
where
    M: Fn(&GValue, bool) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 3 {
            return None;
        }
        (self.callback)(&params[0], params[1].get_boolean());
        None
    }
}

/// VOID:STRING_BOXED_BOXED marshaller.
pub struct VoidStringBoxedBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringBoxedBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringBoxedBoxed<M>
where
    M: Fn(&GValue, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 4 {
            return None;
        }
        let s = params[1].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s);
        None
    }
}

/// VOID:STRING_STRING_VARIANT marshaller.
pub struct VoidStringStringVariant<M>
where
    M: Fn(&GValue, &str, &str) + Send + Sync,
{
    callback: M,
}

impl<M> VoidStringStringVariant<M>
where
    M: Fn(&GValue, &str, &str) + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for VoidStringStringVariant<M>
where
    M: Fn(&GValue, &str, &str) + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 4 {
            return None;
        }
        let s1 = params[1].get_string().unwrap_or("").to_string();
        let s2 = params[2].get_string().unwrap_or("").to_string();
        (self.callback)(&params[0], &s1, &s2);
        None
    }
}

/// INT:BOXED marshaller.
pub struct IntBoxed<M>
where
    M: Fn(&GValue) -> i32 + Send + Sync,
{
    callback: M,
}

impl<M> IntBoxed<M>
where
    M: Fn(&GValue) -> i32 + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for IntBoxed<M>
where
    M: Fn(&GValue) -> i32 + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() < 2 {
            return None;
        }
        let result = (self.callback)(&params[0]);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_INT);
        v.set_int(result);
        Some(v)
    }
}

/// BOOLEAN:OBJECT_FLAGS marshaller.
pub struct BooleanObjectFlags<M>
where
    M: Fn(&GValue, &GValue, u32) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanObjectFlags<M>
where
    M: Fn(&GValue, &GValue, u32) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanObjectFlags<M>
where
    M: Fn(&GValue, &GValue, u32) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        let result = (self.callback)(&params[0], &params[1], params[2].get_uint());
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// BOOLEAN:OBJECT_OBJECT marshaller.
pub struct BooleanObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanObjectObject<M>
where
    M: Fn(&GValue, &GValue, &GValue) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        let result = (self.callback)(&params[0], &params[1], &params[2]);
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

/// BOOLEAN:POINTER_INT marshaller.
pub struct BooleanPointerInt<M>
where
    M: Fn(&GValue, i32) -> bool + Send + Sync,
{
    callback: M,
}

impl<M> BooleanPointerInt<M>
where
    M: Fn(&GValue, i32) -> bool + Send + Sync,
{
    pub fn new(callback: M) -> Self {
        Self { callback }
    }
}

impl<M> Marshaller for BooleanPointerInt<M>
where
    M: Fn(&GValue, i32) -> bool + Send + Sync,
{
    fn marshal(&self, params: &[GValue]) -> Option<GValue> {
        if params.len() != 3 {
            return None;
        }
        let result = (self.callback)(&params[0], params[2].get_int());
        let mut v = GValue::for_type(crate::gtype::G_TYPE_BOOLEAN);
        v.set_boolean(result);
        Some(v)
    }
}

// ──────────────────────────── Tests ───────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gtype::type_init;

    #[test]
    fn test_boolean_object() {
        type_init();
        let m = BooleanObject::new(|_inst, _obj| true);
        let v1 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let v2 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let result = m.marshal(&[v1, v2]);
        assert!(result.is_some());
        assert!(result.unwrap().get_boolean());
    }

    #[test]
    fn test_boolean_void() {
        type_init();
        let m = VoidVoid::new(|_inst| {});
        let v1 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let result = m.marshal(&[v1]);
        assert!(result.is_none());
    }

    #[test]
    fn test_void_uint_uint_uint() {
        type_init();
        let m = VoidUintUintUint::new(|_inst, a, b, c| {
            assert_eq!(a, 1);
            assert_eq!(b, 2);
            assert_eq!(c, 3);
        });
        let v0 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let mut v1 = GValue::for_type(crate::gtype::G_TYPE_UINT);
        v1.set_uint(1);
        let mut v2 = GValue::for_type(crate::gtype::G_TYPE_UINT);
        v2.set_uint(2);
        let mut v3 = GValue::for_type(crate::gtype::G_TYPE_UINT);
        v3.set_uint(3);
        let result = m.marshal(&[v0, v1, v2, v3]);
        assert!(result.is_none());
    }

    #[test]
    fn test_int_object() {
        type_init();
        let m = IntObject::new(|_inst, _obj| 42);
        let v1 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let v2 = GValue::for_type(crate::gtype::G_TYPE_INT);
        let result = m.marshal(&[v1, v2]).unwrap();
        assert_eq!(result.get_int(), 42);
    }

    #[test]
    fn test_wrong_param_count() {
        type_init();
        let m = BooleanObject::new(|_, _| true);
        let result = m.marshal(&[]);
        assert!(result.is_none());
    }
}
