//! GIO themed icon matching `gio/gthemedicon.h` /
//! `gio/gthemedicon.c`.
//!
//! Upstream `GThemedIcon` is a `GObject` subclass implementing `GIcon`.
//! It contains a list of icon names with optional default fallbacks
//! (shortening at `-` characters) and symbolic variant support.
//!
//! Provides:
//! - `ThemedIcon` struct (names + use_default_fallbacks).
//! - `new(iconname)`, `new_with_default_fallbacks(iconname)`,
//!   `new_from_names(names)`.
//! - `names()`, `prepend_name()`, `append_name()`.
//! - `hash()`, `equal()`, `to_string()`.
//!
//! Fully `no_std` compatible using `alloc`.

use alloc::string::String;
use alloc::string::ToString;
use alloc::vec::Vec;

/// A themed icon (`GThemedIcon`).
///
/// Contains a list of icon names that can be looked up in an icon
/// theme. Supports default fallbacks (shortening at `-` characters)
/// and symbolic variant generation.
///
/// Plain struct port of the upstream GObject+GIcon subclass.
#[derive(Clone, Debug)]
pub struct ThemedIcon {
    /// The initial names provided by the user (before fallback expansion).
    init_names: Vec<String>,
    /// The expanded names list (with fallbacks and variants).
    names: Vec<String>,
    /// Whether to use default fallbacks (shortening at `-`).
    use_default_fallbacks: bool,
}

impl ThemedIcon {
    /// Creates a new themed icon for the given icon name.
    ///
    /// Mirrors `g_themed_icon_new`.
    pub fn new(iconname: &str) -> Self {
        let init_names = vec![iconname.to_string()];
        let names = Self::expand_names(&init_names, false);
        ThemedIcon {
            init_names,
            names,
            use_default_fallbacks: false,
        }
    }

    /// Creates a new themed icon with default fallbacks.
    ///
    /// The fallbacks are generated by shortening the icon name at `-`
    /// characters. For example, `"gnome-dev-cdrom-audio"` produces
    /// `["gnome-dev-cdrom-audio", "gnome-dev-cdrom", "gnome-dev", "gnome"]`.
    ///
    /// Mirrors `g_themed_icon_new_with_default_fallbacks`.
    pub fn new_with_default_fallbacks(iconname: &str) -> Self {
        let init_names = vec![iconname.to_string()];
        let names = Self::expand_names(&init_names, true);
        ThemedIcon {
            init_names,
            names,
            use_default_fallbacks: true,
        }
    }

    /// Creates a new themed icon from multiple names.
    ///
    /// Mirrors `g_themed_icon_new_from_names`.
    pub fn new_from_names(names: &[&str]) -> Self {
        let init_names: Vec<String> = names.iter().map(|s| s.to_string()).collect();
        let expanded = Self::expand_names(&init_names, false);
        ThemedIcon {
            init_names,
            names: expanded,
            use_default_fallbacks: false,
        }
    }

    /// Gets the list of icon names (including fallbacks and variants).
    ///
    /// Mirrors `g_themed_icon_get_names`.
    pub fn names(&self) -> &[String] {
        &self.names
    }

    /// Prepends a name to the list of init names and regenerates.
    ///
    /// Mirrors `g_themed_icon_prepend_name`.
    pub fn prepend_name(&mut self, iconname: &str) {
        self.init_names.insert(0, iconname.to_string());
        self.names = Self::expand_names(&self.init_names, self.use_default_fallbacks);
    }

    /// Appends a name to the list of init names and regenerates.
    ///
    /// Mirrors `g_themed_icon_append_name`.
    pub fn append_name(&mut self, iconname: &str) {
        self.init_names.push(iconname.to_string());
        self.names = Self::expand_names(&self.init_names, self.use_default_fallbacks);
    }

    /// Computes a hash for the icon (XOR of name hashes).
    ///
    /// Mirrors `g_themed_icon_hash`.
    pub fn hash(&self) -> u32 {
        let mut h: u32 = 0;
        for name in &self.names {
            h ^= simple_hash(name);
        }
        h
    }

    /// Checks if two themed icons are equal (same names list).
    ///
    /// Mirrors `g_themed_icon_equal`.
    pub fn equal(&self, other: &Self) -> bool {
        self.names == other.names
    }

    /// Serializes to a string representation.
    ///
    /// For a single name: just the name.
    /// For multiple names: `". name1 name2 ..."`.
    ///
    /// Mirrors `g_icon_to_string` for themed icons.
    pub fn to_string(&self) -> String {
        if self.names.len() == 1 {
            self.names[0].clone()
        } else {
            let mut s = String::from(". ");
            for (i, name) in self.names.iter().enumerate() {
                if i > 0 {
                    s.push(' ');
                }
                s.push_str(name);
            }
            s
        }
    }

    /// Expands init names into the full names list with fallbacks
    /// and symbolic variants.
    ///
    /// Mirrors `g_themed_icon_update_names`.
    fn expand_names(init_names: &[String], use_default_fallbacks: bool) -> Vec<String> {
        let mut names: Vec<String> = Vec::new();
        let mut variants: Vec<String> = Vec::new();

        for init_name in init_names {
            let is_symbolic = init_name.ends_with("-symbolic");
            let base_name = if is_symbolic {
                &init_name[..init_name.len() - 9]
            } else {
                init_name.as_str()
            };

            // Skip if already in names list.
            let name_to_add = if is_symbolic {
                init_name.clone()
            } else {
                base_name.to_string()
            };
            if names.contains(&name_to_add) {
                continue;
            }
            names.push(name_to_add);

            // Add fallbacks by shortening at '-'.
            if use_default_fallbacks {
                let mut last = if is_symbolic {
                    base_name.to_string()
                } else {
                    base_name.to_string()
                };

                while let Some(dash_pos) = last.rfind('-') {
                    let fallback_base = &last[..dash_pos];
                    let fallback = if is_symbolic {
                        format!("{}-symbolic", fallback_base)
                    } else {
                        fallback_base.to_string()
                    };
                    if names.contains(&fallback) {
                        break;
                    }
                    names.push(fallback);
                    last = fallback_base.to_string();
                }
            }
        }

        // Generate symbolic/regular variants.
        for name in &names {
            let is_symbolic = name.ends_with("-symbolic");
            let variant = if is_symbolic {
                name[..name.len() - 9].to_string()
            } else {
                format!("{}-symbolic", name)
            };
            if !names.contains(&variant) && !variants.contains(&variant) {
                variants.push(variant);
            }
        }

        names.extend(variants);
        names
    }
}

/// Simple string hash (FNV-1a-like) for icon name hashing.
fn simple_hash(s: &str) -> u32 {
    let mut h: u32 = 5381;
    for b in s.bytes() {
        h = h.wrapping_mul(33).wrapping_add(b as u32);
    }
    h
}

// ──────────────────────────── Tests ───────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_single() {
        let icon = ThemedIcon::new("folder");
        let names = icon.names();
        assert!(names.contains(&"folder".to_string()));
    }

    #[test]
    fn test_new_from_names() {
        let icon = ThemedIcon::new_from_names(&["folder", "open"]);
        let names = icon.names();
        assert!(names.contains(&"folder".to_string()));
        assert!(names.contains(&"open".to_string()));
    }

    #[test]
    fn test_default_fallbacks() {
        let icon = ThemedIcon::new_with_default_fallbacks("gnome-dev-cdrom-audio");
        let names: Vec<&str> = icon.names().iter().map(|s| s.as_str()).collect();
        assert!(names.contains(&"gnome-dev-cdrom-audio"));
        assert!(names.contains(&"gnome-dev-cdrom"));
        assert!(names.contains(&"gnome-dev"));
        assert!(names.contains(&"gnome"));
    }

    #[test]
    fn test_no_default_fallbacks() {
        let icon = ThemedIcon::new("gnome-dev-cdrom-audio");
        let names = icon.names();
        // Without fallbacks, only the original + symbolic variant.
        assert!(names.contains(&"gnome-dev-cdrom-audio".to_string()));
        assert!(!names.contains(&"gnome-dev-cdrom".to_string()));
        assert!(!names.contains(&"gnome-dev".to_string()));
    }

    #[test]
    fn test_symbolic_variants() {
        let icon = ThemedIcon::new("folder");
        let names = icon.names();
        assert!(names.contains(&"folder".to_string()));
        assert!(names.contains(&"folder-symbolic".to_string()));
    }

    #[test]
    fn test_symbolic_input() {
        let icon = ThemedIcon::new("folder-symbolic");
        let names = icon.names();
        assert!(names.contains(&"folder-symbolic".to_string()));
        assert!(names.contains(&"folder".to_string()));
    }

    #[test]
    fn test_symbolic_with_fallbacks() {
        let icon = ThemedIcon::new_with_default_fallbacks("gnome-dev-cdrom-symbolic");
        let names: Vec<&str> = icon.names().iter().map(|s| s.as_str()).collect();
        assert!(names.contains(&"gnome-dev-cdrom-symbolic"));
        assert!(names.contains(&"gnome-dev-symbolic"));
        assert!(names.contains(&"gnome-symbolic"));
    }

    #[test]
    fn test_prepend_name() {
        let mut icon = ThemedIcon::new("folder");
        icon.prepend_name("directory");
        let names = icon.names();
        assert_eq!(names[0], "directory");
    }

    #[test]
    fn test_append_name() {
        let mut icon = ThemedIcon::new("folder");
        icon.append_name("open");
        let names = icon.names();
        assert!(names.contains(&"open".to_string()));
    }

    #[test]
    fn test_equal_same() {
        let a = ThemedIcon::new("folder");
        let b = ThemedIcon::new("folder");
        assert!(a.equal(&b));
    }

    #[test]
    fn test_equal_different() {
        let a = ThemedIcon::new("folder");
        let b = ThemedIcon::new("file");
        assert!(!a.equal(&b));
    }

    #[test]
    fn test_to_string_single() {
        let icon = ThemedIcon::new("folder");
        // Single name → just the name (but symbolic variant is also there).
        // With symbolic variants, names has 2 entries, so it uses ". " format.
        let s = icon.to_string();
        assert!(s.contains("folder"));
    }

    #[test]
    fn test_to_string_multiple() {
        let icon = ThemedIcon::new_from_names(&["folder", "open"]);
        let s = icon.to_string();
        assert!(s.starts_with(". "));
        assert!(s.contains("folder"));
        assert!(s.contains("open"));
    }

    #[test]
    fn test_hash_consistency() {
        let a = ThemedIcon::new("folder");
        let b = ThemedIcon::new("folder");
        assert_eq!(a.hash(), b.hash());
    }

    #[test]
    fn test_hash_different() {
        let a = ThemedIcon::new("folder");
        let b = ThemedIcon::new("file");
        assert_ne!(a.hash(), b.hash());
    }

    #[test]
    fn test_clone() {
        let a = ThemedIcon::new("folder");
        let b = a.clone();
        assert!(a.equal(&b));
    }
}
