//! Monitor Manager Private — ported from GNOME Mutter
//!
//! Private structures for CRTC and output assignments used by the monitor manager.
//! These represent configuration snapshots generated by the monitor config manager.
//!
//! Reference: https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/backends/meta-monitor-manager-private.h

use alloc::string::String;

/// Placeholder types for opaque C structures.
#[derive(Debug)]
pub struct MetaCrtc;

#[derive(Debug)]
pub struct MetaCrtcMode;

#[derive(Debug)]
pub struct MetaOutput;

/// CRTC (CRT controller) assignment: a snapshot of CRTC configuration.
/// Contains the CRTC, its mode, layout, transform, and assigned outputs.
#[derive(Debug, Clone)]
pub struct MetaCrtcAssignment {
    /// Opaque CRTC reference.
    pub crtc: u32,
    /// Opaque CRTC mode reference.
    pub mode: u32,
    /// Layout rectangle (x, y, width, height).
    pub layout: (i32, i32, u32, u32),
    /// Monitor transform (rotation/flip).
    pub transform: u32,
    /// Number of assigned outputs (placeholder).
    pub outputs_count: u32,
    /// Backend-private data reference.
    pub backend_private: u32,
}

impl MetaCrtcAssignment {
    /// Create a new CRTC assignment.
    pub fn new(crtc: u32, mode: u32, transform: u32) -> Self {
        MetaCrtcAssignment {
            crtc,
            mode,
            layout: (0, 0, 0, 0),
            transform,
            outputs_count: 0,
            backend_private: 0,
        }
    }
}

impl Default for MetaCrtcAssignment {
    fn default() -> Self {
        Self::new(0, 0, 0)
    }
}

/// Output assignment: a snapshot of connector/output configuration.
/// Contains output properties like DPMS state, underscanning, and color depth.
#[derive(Debug, Clone)]
pub struct MetaOutputAssignment {
    /// Opaque output reference.
    pub output: u32,
    /// Whether this is the primary output.
    pub is_primary: bool,
    /// Presentation mode enabled.
    pub is_presentation: bool,
    /// Underscanning enabled.
    pub is_underscanning: bool,
    /// Maximum BPC property supported.
    pub has_max_bpc: bool,
    /// Maximum bits per channel.
    pub max_bpc: u32,
    /// RGB range (limited or full).
    pub rgb_range: u32,
    /// Color mode (placeholder value).
    pub color_mode: u32,
}

impl MetaOutputAssignment {
    /// Create a new output assignment.
    pub fn new(output: u32) -> Self {
        MetaOutputAssignment {
            output,
            is_primary: false,
            is_presentation: false,
            is_underscanning: false,
            has_max_bpc: false,
            max_bpc: 8,
            rgb_range: 0,
            color_mode: 0,
        }
    }
}

impl Default for MetaOutputAssignment {
    fn default() -> Self {
        Self::new(0)
    }
}
