//! Linux file handle syscalls.
//!
//! RustOS does not expose stable filesystem export handles yet, so handles are
//! runtime-scoped opaque IDs generated by `name_to_handle_at` and consumed by
//! `open_by_handle_at`. They remain valid while the kernel is running and the
//! path still resolves in VFS.

extern crate alloc;

use alloc::collections::BTreeMap;
use alloc::string::String;
use core::sync::atomic::{AtomicU64, Ordering};
use spin::RwLock;

use crate::linux_compat::file_ops;
use crate::linux_compat::types::{Fd, Mode};
use crate::linux_compat::{LinuxError, LinuxResult};
use crate::memory::user_space::UserSpaceMemory;
use crate::process;
use crate::vfs;

const HANDLE_TYPE_RUNTIME_PATH: i32 = 1;
const HANDLE_BYTES: u32 = core::mem::size_of::<u64>() as u32;
const FILE_HANDLE_HEADER: u64 = 8;
const AT_EMPTY_PATH: i32 = 0x1000;
const AT_SYMLINK_FOLLOW: i32 = 0x400;
const VALID_NAME_TO_HANDLE_FLAGS: i32 = AT_EMPTY_PATH | AT_SYMLINK_FOLLOW;

static NEXT_HANDLE: AtomicU64 = AtomicU64::new(1);
static HANDLES: RwLock<BTreeMap<u64, String>> = RwLock::new(BTreeMap::new());

fn current_is_privileged() -> bool {
    let pid = process::current_pid();
    process::get_process_manager()
        .get_process(pid)
        .map(|pcb| pcb.euid == 0)
        .unwrap_or(true)
}

fn read_u32(addr: u64) -> LinuxResult<u32> {
    let mut bytes = [0u8; 4];
    UserSpaceMemory::copy_from_user(addr, &mut bytes).map_err(|_| LinuxError::EFAULT)?;
    Ok(u32::from_ne_bytes(bytes))
}

fn read_i32(addr: u64) -> LinuxResult<i32> {
    let mut bytes = [0u8; 4];
    UserSpaceMemory::copy_from_user(addr, &mut bytes).map_err(|_| LinuxError::EFAULT)?;
    Ok(i32::from_ne_bytes(bytes))
}

fn read_u64(addr: u64) -> LinuxResult<u64> {
    let mut bytes = [0u8; 8];
    UserSpaceMemory::copy_from_user(addr, &mut bytes).map_err(|_| LinuxError::EFAULT)?;
    Ok(u64::from_ne_bytes(bytes))
}

fn write_u32(addr: u64, value: u32) -> LinuxResult<()> {
    UserSpaceMemory::copy_to_user(addr, &value.to_ne_bytes()).map_err(|_| LinuxError::EFAULT)
}

fn write_i32(addr: u64, value: i32) -> LinuxResult<()> {
    UserSpaceMemory::copy_to_user(addr, &value.to_ne_bytes()).map_err(|_| LinuxError::EFAULT)
}

fn write_u64(addr: u64, value: u64) -> LinuxResult<()> {
    UserSpaceMemory::copy_to_user(addr, &value.to_ne_bytes()).map_err(|_| LinuxError::EFAULT)
}

pub fn name_to_handle_at(
    dirfd: Fd,
    pathname: *const u8,
    handle: *mut u8,
    mount_id: *mut i32,
    flags: i32,
) -> LinuxResult<i32> {
    if handle.is_null() || mount_id.is_null() {
        return Err(LinuxError::EFAULT);
    }
    if flags & !VALID_NAME_TO_HANDLE_FLAGS != 0 {
        return Err(LinuxError::EINVAL);
    }

    let path = file_ops::resolve_at_path(dirfd, pathname)?;
    let stat = vfs::vfs_stat(&path).map_err(file_ops::vfs_error_to_linux)?;
    let available = read_u32(handle as u64)?;
    if available < HANDLE_BYTES {
        write_u32(handle as u64, HANDLE_BYTES)?;
        return Err(LinuxError::EOVERFLOW);
    }

    let id = NEXT_HANDLE.fetch_add(1, Ordering::SeqCst);
    HANDLES.write().insert(id, path);

    write_u32(handle as u64, HANDLE_BYTES)?;
    write_i32(handle as u64 + 4, HANDLE_TYPE_RUNTIME_PATH)?;
    write_u64(handle as u64 + FILE_HANDLE_HEADER, id)?;
    write_i32(mount_id as u64, stat_dev_mount_id(stat.rdev))?;
    Ok(0)
}

fn stat_dev_mount_id(dev: u64) -> i32 {
    if dev == 0 {
        1
    } else {
        (dev & 0x7fff_ffff) as i32
    }
}

pub fn open_by_handle_at(_mount_fd: Fd, handle: *mut u8, flags: i32) -> LinuxResult<Fd> {
    if handle.is_null() {
        return Err(LinuxError::EFAULT);
    }
    if !current_is_privileged() {
        return Err(LinuxError::EPERM);
    }

    let handle_bytes = read_u32(handle as u64)?;
    let handle_type = read_i32(handle as u64 + 4)?;
    if handle_type != HANDLE_TYPE_RUNTIME_PATH || handle_bytes != HANDLE_BYTES {
        return Err(LinuxError::ESTALE);
    }

    let id = read_u64(handle as u64 + FILE_HANDLE_HEADER)?;
    let path = HANDLES.read().get(&id).cloned().ok_or(LinuxError::ESTALE)?;
    let vfs_flags = file_ops::linux_flags_to_vfs(flags);
    vfs::vfs_open(&path, vfs_flags, 0 as Mode).map_err(file_ops::vfs_error_to_linux)
}

pub fn init() {
    HANDLES.write().clear();
    NEXT_HANDLE.store(1, Ordering::SeqCst);
}
