//! POSIX signal subsystem — ported from Linux kernel/signal.c
//!
//! Provides signal numbers, SigSet bitmask, SigInfo (siginfo_t), SigAction
//! (struct sigaction), per-task SigPending queues, per-process SigHand tables,
//! and the core delivery / masking routines.  All code is #![no_std].

#![allow(dead_code, unused_variables, unused_imports)]

extern crate alloc;

use alloc::collections::VecDeque;
use alloc::sync::Arc;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use spin::Mutex;

// ---------------------------------------------------------------------------
// Signal numbers (UAPI — matches x86-64 Linux)
// ---------------------------------------------------------------------------

pub const SIGHUP: u32 = 1;
pub const SIGINT: u32 = 2;
pub const SIGQUIT: u32 = 3;
pub const SIGILL: u32 = 4;
pub const SIGTRAP: u32 = 5;
pub const SIGABRT: u32 = 6;
pub const SIGBUS: u32 = 7;
pub const SIGFPE: u32 = 8;
pub const SIGKILL: u32 = 9;
pub const SIGUSR1: u32 = 10;
pub const SIGSEGV: u32 = 11;
pub const SIGUSR2: u32 = 12;
pub const SIGPIPE: u32 = 13;
pub const SIGALRM: u32 = 14;
pub const SIGTERM: u32 = 15;
pub const SIGSTKFLT: u32 = 16;
pub const SIGCHLD: u32 = 17;
pub const SIGCONT: u32 = 18;
pub const SIGSTOP: u32 = 19;
pub const SIGTSTP: u32 = 20;
pub const SIGTTIN: u32 = 21;
pub const SIGTTOU: u32 = 22;
pub const SIGURG: u32 = 23;
pub const SIGXCPU: u32 = 24;
pub const SIGXFSZ: u32 = 25;
pub const SIGVTALRM: u32 = 26;
pub const SIGPROF: u32 = 27;
pub const SIGWINCH: u32 = 28;
pub const SIGIO: u32 = 29;
pub const SIGPWR: u32 = 30;
pub const SIGSYS: u32 = 31;
// Real-time signals: 32–64
pub const SIGRTMIN: u32 = 32;
pub const SIGRTMAX: u32 = 64;
pub const NSIG: u32 = 64;

// Errno codes returned as negative i32
const EINVAL: i32 = 22;
const EPERM: i32 = 1;

// ---------------------------------------------------------------------------
// SigSet — 64-bit bitmask (one bit per signal)
// ---------------------------------------------------------------------------

/// Signal bitmask.  Bit N-1 represents signal N (1-indexed, N ∈ [1,64]).
#[derive(Clone, Copy, Default, Debug, PartialEq, Eq)]
pub struct SigSet(pub u64);

impl SigSet {
    /// Empty set — no signals pending / blocked.
    #[inline]
    pub fn empty() -> Self {
        SigSet(0)
    }

    /// Full set — all 64 signals set.
    #[inline]
    pub fn full() -> Self {
        SigSet(u64::MAX)
    }

    /// Add signal `sig` (1-indexed) to the set.
    #[inline]
    pub fn add(&mut self, sig: u32) {
        if sig >= 1 && sig <= NSIG {
            self.0 |= 1u64 << (sig - 1);
        }
    }

    /// Remove signal `sig` from the set.
    #[inline]
    pub fn del(&mut self, sig: u32) {
        if sig >= 1 && sig <= NSIG {
            self.0 &= !(1u64 << (sig - 1));
        }
    }

    /// Test whether signal `sig` is in the set.
    #[inline]
    pub fn has(&self, sig: u32) -> bool {
        if sig >= 1 && sig <= NSIG {
            self.0 & (1u64 << (sig - 1)) != 0
        } else {
            false
        }
    }

    /// Bitwise OR of two sets.
    #[inline]
    pub fn or(&self, other: &SigSet) -> SigSet {
        SigSet(self.0 | other.0)
    }

    /// Bitwise AND of two sets.
    #[inline]
    pub fn and(&self, other: &SigSet) -> SigSet {
        SigSet(self.0 & other.0)
    }

    /// `self & ~other` — signals in self that are not in other.
    #[inline]
    pub fn andnot(&self, other: &SigSet) -> SigSet {
        SigSet(self.0 & !other.0)
    }

    /// Return the lowest-numbered pending signal (1-indexed), or None if empty.
    #[inline]
    pub fn next_pending(&self) -> Option<u32> {
        if self.0 == 0 {
            None
        } else {
            // trailing_zeros gives bit index (0-based); signal is index+1
            Some(self.0.trailing_zeros() + 1)
        }
    }

    /// True if the set has no signals.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.0 == 0
    }
}

// ---------------------------------------------------------------------------
// SiCode — si_code values (subset matching Linux SI_* constants)
// ---------------------------------------------------------------------------

/// `si_code` discriminant that identifies the signal origin.
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(i32)]
pub enum SiCode {
    /// Sent by kill() / raise() from user space.
    User = 0,
    /// Sent by the kernel itself (e.g. SIGSEGV on page fault).
    Kernel = 0x80,
    /// Sent via sigqueue().
    Queue = -1,
    /// Generated by timer expiry (POSIX timers).
    Timer = -2,
    /// Generated by message-queue state change.
    MesgQ = -3,
    /// Async I/O completion.
    Asyncio = -4,
    /// Queued SIGIO.
    SigIo = -5,
}

// ---------------------------------------------------------------------------
// SigInfo — matches Linux kernel_siginfo_t layout (C ABI)
// ---------------------------------------------------------------------------

/// Per-signal metadata passed to SA_SIGINFO handlers and queued with RT signals.
/// Layout intentionally matches `struct siginfo` (abbreviated) on x86-64.
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct SigInfo {
    /// Signal number (SIGXXX constant).
    pub si_signo: u32,
    /// Errno value associated with the signal (usually 0).
    pub si_errno: i32,
    /// Signal code — encodes the origin (see [`SiCode`]).
    pub si_code: i32,
    /// Sending process PID (when applicable).
    pub si_pid: u32,
    /// Sending process real UID.
    pub si_uid: u32,
    /// Faulting address (SIGSEGV / SIGBUS / SIGILL / SIGFPE).
    pub si_addr: u64,
    /// Exit status / signal (SIGCHLD).
    pub si_status: i32,
    /// Signal value (sigqueue / RT signals).
    pub si_value: i64,
}

impl SigInfo {
    /// Construct a minimal SigInfo with explicit code.
    pub fn new(sig: u32, code: SiCode) -> Self {
        SigInfo {
            si_signo: sig,
            si_errno: 0,
            si_code: code as i32,
            si_pid: 0,
            si_uid: 0,
            si_addr: 0,
            si_status: 0,
            si_value: 0,
        }
    }

    /// Construct a kernel-originated SigInfo (SI_KERNEL).
    pub fn from_kernel(sig: u32) -> Self {
        Self::new(sig, SiCode::Kernel)
    }

    /// Construct a user-space-originated SigInfo (SI_USER).
    pub fn from_user(sig: u32, pid: u32, uid: u32) -> Self {
        SigInfo {
            si_signo: sig,
            si_errno: 0,
            si_code: SiCode::User as i32,
            si_pid: pid,
            si_uid: uid,
            si_addr: 0,
            si_status: 0,
            si_value: 0,
        }
    }
}

// ---------------------------------------------------------------------------
// SaFlags — matches SA_* flag bits in Linux struct sigaction.sa_flags
// ---------------------------------------------------------------------------

/// Flags controlling signal-handler behaviour (sa_flags).
///
/// Uses a plain u64 newtype + associated constants to stay compatible
/// even if the `bitflags` macro is unavailable in a no_std context.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct SaFlags(pub u64);

impl SaFlags {
    /// Do not send SIGCHLD when a child stops (only when it terminates).
    pub const NOCLDSTOP: SaFlags = SaFlags(1 << 0);
    /// Do not create zombie processes (auto-reap children).
    pub const NOCLDWAIT: SaFlags = SaFlags(1 << 1);
    /// Invoke handler with three arguments (sa_sigaction style).
    pub const SIGINFO: SaFlags = SaFlags(1 << 2);
    /// Use alternate signal stack (sigaltstack).
    pub const ONSTACK: SaFlags = SaFlags(1 << 3);
    /// Automatically restart certain syscalls interrupted by this signal.
    pub const RESTART: SaFlags = SaFlags(1 << 4);
    /// Do not block the signal while its handler is executing.
    pub const NODEFER: SaFlags = SaFlags(1 << 5);
    /// Reset handler to SIG_DFL before invoking it (one-shot semantics).
    pub const RESETHAND: SaFlags = SaFlags(1 << 6);

    #[inline]
    pub fn contains(self, flag: SaFlags) -> bool {
        self.0 & flag.0 == flag.0
    }
    #[inline]
    pub fn insert(&mut self, flag: SaFlags) {
        self.0 |= flag.0;
    }
    #[inline]
    pub fn remove(&mut self, flag: SaFlags) {
        self.0 &= !flag.0;
    }

    #[inline]
    pub fn from_bits_truncate(bits: u64) -> Self {
        // Mask to only known bits
        let known = SaFlags::NOCLDSTOP.0
            | SaFlags::NOCLDWAIT.0
            | SaFlags::SIGINFO.0
            | SaFlags::ONSTACK.0
            | SaFlags::RESTART.0
            | SaFlags::NODEFER.0
            | SaFlags::RESETHAND.0;
        SaFlags(bits & known)
    }
}

impl core::ops::BitOr for SaFlags {
    type Output = SaFlags;
    fn bitor(self, rhs: SaFlags) -> SaFlags {
        SaFlags(self.0 | rhs.0)
    }
}

impl core::ops::BitAnd for SaFlags {
    type Output = SaFlags;
    fn bitand(self, rhs: SaFlags) -> SaFlags {
        SaFlags(self.0 & rhs.0)
    }
}

// ---------------------------------------------------------------------------
// SigHandler — disposition stored in SigHand table
// ---------------------------------------------------------------------------

/// Per-signal disposition (analogous to sa_handler / sa_sigaction union).
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum SigHandler {
    /// SIG_DFL — apply the default disposition for the signal.
    Default,
    /// SIG_IGN — silently discard the signal.
    Ignore,
    /// User-space handler function at virtual address `vaddr`.
    Handler(u64),
}

// ---------------------------------------------------------------------------
// SigAction — full action entry (one per slot in SigHand::action[])
// ---------------------------------------------------------------------------

/// Complete action for a signal: handler + flags + blocked-during-handler mask.
/// Corresponds to `struct sigaction` in POSIX / Linux.
#[derive(Clone, Copy, Debug)]
pub struct SigAction {
    /// How to handle the signal.
    pub handler: SigHandler,
    /// Behavioural flags (SA_RESTART, SA_SIGINFO, …).
    pub flags: SaFlags,
    /// Additional signals to block while the handler executes.
    pub mask: SigSet,
}

impl Default for SigAction {
    fn default() -> Self {
        SigAction {
            handler: SigHandler::Default,
            flags: SaFlags::default(),
            mask: SigSet::empty(),
        }
    }
}

// ---------------------------------------------------------------------------
// SigDefaultAction — Linux default disposition table
// ---------------------------------------------------------------------------

/// Default disposition applied when `SigHandler::Default` is in effect.
#[derive(Debug, PartialEq)]
pub enum SigDefaultAction {
    /// Terminate the process.
    Terminate,
    /// Terminate and generate a core dump.
    CoreDump,
    /// Silently ignore the signal.
    Ignore,
    /// Stop (suspend) the process.
    Stop,
    /// Continue a stopped process.
    Continue,
}

/// Map a signal number to its default disposition.
/// Matches Linux `sig_kernel_*` tables in include/linux/signal.h.
pub fn sig_default_action(sig: u32) -> SigDefaultAction {
    match sig {
        // Core-dump signals
        SIGQUIT | SIGILL | SIGTRAP | SIGABRT | SIGBUS | SIGFPE | SIGSEGV | SIGXCPU | SIGXFSZ
        | SIGSYS => SigDefaultAction::CoreDump,

        // Ignored by default
        SIGCHLD | SIGURG | SIGWINCH => SigDefaultAction::Ignore,

        // Stop signals
        SIGSTOP | SIGTSTP | SIGTTIN | SIGTTOU => SigDefaultAction::Stop,

        // Continue
        SIGCONT => SigDefaultAction::Continue,

        // Everything else terminates
        _ => SigDefaultAction::Terminate,
    }
}

/// Returns true for signals that cannot be caught, blocked, or ignored.
#[inline]
pub fn sig_unblockable(sig: u32) -> bool {
    sig == SIGKILL || sig == SIGSTOP
}

// ---------------------------------------------------------------------------
// SigPending — per-task pending signal queue
// ---------------------------------------------------------------------------

/// Per-task set of pending signals.
///
/// `signal` is a fast-path bitmask; `list` holds full [`SigInfo`] for RT
/// signals (SIGRTMIN–SIGRTMAX) and for standard signals delivered with extra
/// metadata via `sigqueue()`.
pub struct SigPending {
    /// Bitmask of pending signals (one bit per signal 1–64).
    pub signal: SigSet,
    /// Ordered queue of pending SigInfo records.
    pub list: VecDeque<SigInfo>,
}

impl SigPending {
    pub fn new() -> Self {
        SigPending {
            signal: SigSet::empty(),
            list: VecDeque::new(),
        }
    }

    /// Enqueue a signal.
    ///
    /// For standard (non-RT) signals the bitmask coalesces duplicates; only
    /// the first SigInfo for each standard signal is retained.  RT signals
    /// always enqueue (POSIX real-time queuing semantics).
    pub fn add(&mut self, sig: u32, info: SigInfo) {
        let already = self.signal.has(sig);
        self.signal.add(sig);

        if sig >= SIGRTMIN {
            // RT signals queue indefinitely
            self.list.push_back(info);
        } else if !already {
            // Standard signal: only queue if not already pending
            self.list.push_back(info);
        }
        // If standard signal is already pending, drop the duplicate info
    }

    /// Dequeue the next pending signal, returning its number and info.
    ///
    /// Standard signals are dequeued in order of signal number; RT signals
    /// are dequeued FIFO within priority order.
    pub fn dequeue(&mut self) -> Option<(u32, SigInfo)> {
        let sig = self.signal.next_pending()?;

        // Find and remove the matching SigInfo from the list
        if let Some(pos) = self.list.iter().position(|i| i.si_signo == sig) {
            let info = self.list.remove(pos).unwrap();

            // Clear bitmask bit only if no more queued infos for this signal
            let still_queued = self.list.iter().any(|i| i.si_signo == sig);
            if !still_queued {
                self.signal.del(sig);
            }

            Some((sig, info))
        } else {
            // Bitmask set but no info record — synthesise a minimal one
            self.signal.del(sig);
            Some((sig, SigInfo::from_kernel(sig)))
        }
    }

    pub fn is_empty(&self) -> bool {
        self.signal.is_empty()
    }

    pub fn has_signal(&self, sig: u32) -> bool {
        self.signal.has(sig)
    }
}

impl Default for SigPending {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// SigHand — per-process signal handler table (shared across threads)
// ---------------------------------------------------------------------------

/// Per-process signal handler table, shared (via Arc) across all threads in a
/// thread group.  Mirrors Linux `struct sighand_struct`.
pub struct SigHand {
    /// One action entry per signal (indexed by sig-1).
    pub action: [SigAction; 64],
    /// Reference count (manual, mirrors Linux sighand_struct.count).
    pub count: AtomicU32,
    /// Protects `action` during `sigaction()` / `exec()`.
    pub lock: Mutex<()>,
}

impl SigHand {
    pub fn new() -> Self {
        SigHand {
            action: [SigAction::default(); 64],
            count: AtomicU32::new(1),
            lock: Mutex::new(()),
        }
    }

    /// Get the action for signal `sig` (1-indexed).
    pub fn get(&self, sig: u32) -> SigAction {
        if sig >= 1 && sig <= NSIG {
            let _g = self.lock.lock();
            self.action[(sig - 1) as usize]
        } else {
            SigAction::default()
        }
    }

    /// Set the action for signal `sig` (1-indexed).
    pub fn set(&self, sig: u32, act: SigAction) {
        if sig >= 1 && sig <= NSIG {
            let _g = self.lock.lock();
            // SAFETY: we hold the mutex; [SigAction; 64] is Copy, no aliasing issues.
            // In a no_std context we work around the shared-ref constraint by using
            // an unsafe write — the Mutex above provides the required exclusion.
            let ptr = &self.action[(sig - 1) as usize] as *const SigAction as *mut SigAction;
            unsafe { ptr.write(act) };
        }
    }

    /// Duplicate the handler table for `fork()` / `clone()` without CLONE_SIGHAND.
    pub fn dup(&self) -> SigHand {
        let _g = self.lock.lock();
        SigHand {
            action: self.action, // [SigAction; 64] is Copy
            count: AtomicU32::new(1),
            lock: Mutex::new(()),
        }
    }
}

impl Default for SigHand {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Core signal delivery routines
// ---------------------------------------------------------------------------

/// Complete signal delivery: update the pending bitmask and enqueue the info.
///
/// Mirrors Linux `complete_signal()` (simplified — no group-stop handling).
pub fn complete_signal(sig: u32, info: SigInfo, pending: &mut SigPending, blocked: &SigSet) {
    // SIGKILL/SIGSTOP are always delivered regardless of blocked mask
    if !sig_unblockable(sig) && blocked.has(sig) {
        // Signal is blocked — still enqueue (deliver when unblocked)
    }
    pending.add(sig, info);
}

/// Queue a signal to a task.
///
/// Returns 0 on success, -EINVAL for an invalid signal number.
/// Mirrors Linux `send_signal_info()`.
pub fn send_signal_info(
    sig: u32,
    info: SigInfo,
    task_pending: &Mutex<SigPending>,
    blocked: &SigSet,
) -> i32 {
    if sig < 1 || sig > NSIG {
        return -(EINVAL);
    }

    let mut pending = task_pending.lock();
    complete_signal(sig, info, &mut *pending, blocked);
    0
}

/// Force-deliver a signal, bypassing SIG_IGN and the blocked mask.
///
/// Used for fatal hardware exceptions (SIGSEGV, SIGBUS) where the kernel must
/// act regardless of the process's signal disposition.
pub fn force_sig(sig: u32, task_pending: &Mutex<SigPending>) {
    let info = SigInfo::from_kernel(sig);
    let mut pending = task_pending.lock();
    // Force delivery — ignore blocked mask and any SIG_IGN disposition
    pending.add(sig, info);
}

/// Dequeue the next unblocked pending signal.
///
/// Mirrors Linux `dequeue_signal()`.  Returns (signo, SigInfo) for the
/// lowest-numbered unblocked pending signal, or None if nothing is deliverable.
pub fn dequeue_signal(pending: &mut SigPending, blocked: &SigSet) -> Option<(u32, SigInfo)> {
    // Find lowest unblocked pending signal
    let deliverable = pending.signal.andnot(blocked);
    let sig = deliverable.next_pending()?;

    // Remove from the queue for this specific signal
    if let Some(pos) = pending.list.iter().position(|i| i.si_signo == sig) {
        let info = pending.list.remove(pos).unwrap();

        let still_queued = pending.list.iter().any(|i| i.si_signo == sig);
        if !still_queued {
            pending.signal.del(sig);
        }

        Some((sig, info))
    } else {
        pending.signal.del(sig);
        Some((sig, SigInfo::from_kernel(sig)))
    }
}

/// Return true if the task has any unblocked pending signal.
///
/// Fast-path check done before re-entering user space.
#[inline]
pub fn signal_pending(pending: &SigPending, blocked: &SigSet) -> bool {
    !pending.signal.andnot(blocked).is_empty()
}

// ---------------------------------------------------------------------------
// sigprocmask — manipulate process signal mask
// ---------------------------------------------------------------------------

/// Argument to [`sigprocmask`] that controls how the blocked set is updated.
/// Matches Linux SIG_BLOCK / SIG_UNBLOCK / SIG_SETMASK values.
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(i32)]
pub enum SigprocmaskHow {
    /// Add signals in `nset` to the current blocked set.
    Block = 0,
    /// Remove signals in `nset` from the current blocked set.
    Unblock = 1,
    /// Replace the blocked set with `nset`.
    Setmask = 2,
}

/// Implements the `sigprocmask(2)` syscall.
///
/// * `how`     — operation (Block / Unblock / Setmask).
/// * `nset`    — new signal set; if None only the old mask is read back.
/// * `blocked` — the task's current blocked mask (mutated in place).
///
/// Returns 0 on success, -EINVAL if `how` is invalid.
pub fn sigprocmask(how: SigprocmaskHow, nset: Option<&SigSet>, blocked: &mut SigSet) -> i32 {
    if let Some(new) = nset {
        match how {
            SigprocmaskHow::Block => {
                // SIGKILL and SIGSTOP cannot be blocked — mask them out
                let mut add = *new;
                add.del(SIGKILL);
                add.del(SIGSTOP);
                *blocked = blocked.or(&add);
            }
            SigprocmaskHow::Unblock => {
                *blocked = blocked.andnot(new);
            }
            SigprocmaskHow::Setmask => {
                let mut set = *new;
                set.del(SIGKILL);
                set.del(SIGSTOP);
                *blocked = set;
            }
        }
    }
    0
}

// ---------------------------------------------------------------------------
// do_sigaction — install / query a signal action
// ---------------------------------------------------------------------------

/// Implements the `sigaction(2)` syscall.
///
/// * `sig`     — signal number (1–NSIG, not SIGKILL/SIGSTOP).
/// * `act`     — new action to install, or None to query only.
/// * `oact`    — written with the previous action if Some(…).
/// * `sighand` — the process's shared signal handler table.
///
/// Returns 0 on success, -EINVAL for invalid arguments.
pub fn do_sigaction(
    sig: u32,
    act: Option<SigAction>,
    oact: &mut Option<SigAction>,
    sighand: &SigHand,
) -> i32 {
    if sig < 1 || sig > NSIG {
        return -(EINVAL);
    }
    // SIGKILL and SIGSTOP cannot have their disposition changed
    if sig_unblockable(sig) && act.is_some() {
        return -(EINVAL);
    }

    // Save old action
    *oact = Some(sighand.get(sig));

    // Install new action
    if let Some(mut new_act) = act {
        // If installing SIG_IGN or SIG_DFL, clear the handler mask per POSIX
        if new_act.handler == SigHandler::Ignore || new_act.handler == SigHandler::Default {
            new_act.mask = SigSet::empty();
        }
        // A handler cannot block itself unless SA_NODEFER is set
        if !new_act.flags.contains(SaFlags::NODEFER) {
            if let SigHandler::Handler(_) = new_act.handler {
                new_act.mask.add(sig);
            }
        }
        sighand.set(sig, new_act);
    }

    0
}

// ---------------------------------------------------------------------------
// Unit tests (run with `cargo test` in a hosted environment)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sigset_basic() {
        let mut s = SigSet::empty();
        assert!(!s.has(SIGINT));
        s.add(SIGINT);
        assert!(s.has(SIGINT));
        s.del(SIGINT);
        assert!(!s.has(SIGINT));
    }

    #[test]
    fn sigset_next_pending() {
        let mut s = SigSet::empty();
        assert_eq!(s.next_pending(), None);
        s.add(SIGTERM);
        s.add(SIGINT);
        // SIGINT = 2, SIGTERM = 15 — lowest should be SIGINT
        assert_eq!(s.next_pending(), Some(SIGINT));
    }

    #[test]
    fn sigset_andnot() {
        let mut a = SigSet::empty();
        let mut b = SigSet::empty();
        a.add(SIGINT);
        a.add(SIGTERM);
        b.add(SIGINT);
        let c = a.andnot(&b);
        assert!(!c.has(SIGINT));
        assert!(c.has(SIGTERM));
    }

    #[test]
    fn sigset_full_has_all() {
        let full = SigSet::full();
        for sig in 1..=NSIG {
            assert!(full.has(sig), "full set missing sig {sig}");
        }
    }

    #[test]
    fn sig_pending_standard_coalesces() {
        let mut p = SigPending::new();
        p.add(SIGINT, SigInfo::from_kernel(SIGINT));
        p.add(SIGINT, SigInfo::from_kernel(SIGINT)); // duplicate
        let (s, _) = p.dequeue().unwrap();
        assert_eq!(s, SIGINT);
        assert!(p.dequeue().is_none()); // coalesced: only one SIGINT
    }

    #[test]
    fn sig_pending_rt_queues() {
        let mut p = SigPending::new();
        p.add(SIGRTMIN, SigInfo::from_kernel(SIGRTMIN));
        p.add(SIGRTMIN, SigInfo::from_kernel(SIGRTMIN));
        assert!(p.dequeue().is_some());
        assert!(p.dequeue().is_some()); // RT signals queue
    }

    #[test]
    fn dequeue_respects_blocked() {
        let mut p = SigPending::new();
        let mut blocked = SigSet::empty();
        blocked.add(SIGINT);
        p.add(SIGINT, SigInfo::from_kernel(SIGINT));
        p.add(SIGTERM, SigInfo::from_kernel(SIGTERM));
        // SIGINT is blocked — should get SIGTERM first
        let (sig, _) = dequeue_signal(&mut p, &blocked).unwrap();
        assert_eq!(sig, SIGTERM);
    }

    #[test]
    fn sigprocmask_block_cannot_block_sigkill() {
        let mut blocked = SigSet::empty();
        let mut new_set = SigSet::full();
        sigprocmask(SigprocmaskHow::Setmask, Some(&new_set), &mut blocked);
        assert!(!blocked.has(SIGKILL));
        assert!(!blocked.has(SIGSTOP));
    }

    #[test]
    fn do_sigaction_rejects_sigkill() {
        let sh = SigHand::new();
        let act = SigAction {
            handler: SigHandler::Ignore,
            ..Default::default()
        };
        let mut oact = None;
        let ret = do_sigaction(SIGKILL, Some(act), &mut oact, &sh);
        assert_eq!(ret, -(EINVAL));
    }

    #[test]
    fn do_sigaction_roundtrip() {
        let sh = SigHand::new();
        let act = SigAction {
            handler: SigHandler::Handler(0xdeadbeef),
            flags: SaFlags::RESTART,
            mask: SigSet::empty(),
        };
        let mut oact = None;
        assert_eq!(do_sigaction(SIGUSR1, Some(act), &mut oact, &sh), 0);
        if let SigHandler::Handler(addr) = sh.get(SIGUSR1).handler {
            assert_eq!(addr, 0xdeadbeef);
        } else {
            panic!("handler not installed");
        }
        // SIGUSR1 should be added to its own mask (SA_NODEFER not set)
        assert!(sh.get(SIGUSR1).mask.has(SIGUSR1));
    }

    #[test]
    fn sig_default_actions() {
        assert_eq!(sig_default_action(SIGSEGV), SigDefaultAction::CoreDump);
        assert_eq!(sig_default_action(SIGCHLD), SigDefaultAction::Ignore);
        assert_eq!(sig_default_action(SIGSTOP), SigDefaultAction::Stop);
        assert_eq!(sig_default_action(SIGCONT), SigDefaultAction::Continue);
        assert_eq!(sig_default_action(SIGTERM), SigDefaultAction::Terminate);
    }

    #[test]
    fn force_sig_delivers_despite_ignore() {
        // force_sig bypasses disposition checks — just verifies it enqueues
        let pending: Mutex<SigPending> = Mutex::new(SigPending::new());
        force_sig(SIGSEGV, &pending);
        assert!(pending.lock().has_signal(SIGSEGV));
    }
}
